name: Gmail Notification Workflow

on:
  workflow_call:
    inputs:
      PRODUCT_NAME:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
      ARTIFACT_BRANCH:
        type: string
        required: true
      ARTIFACT_VERSION:
        type: string
        required: true
      DEPLOYMENT_STATUS:
        type: string
        required: true

    secrets:
      GMAIL_USER:
        required: true
      GMAIL_PASS:
        required: true
      EMAIL_TO:
        required: true

jobs:
  send-gmail:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mail Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp-mta mailutils jq

      - name: Configure and Send Email
        run: |
          echo "defaults" > ~/.msmtprc
          echo "auth           on" >> ~/.msmtprc
          echo "tls            on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "account        gmail" >> ~/.msmtprc
          echo "host           smtp.gmail.com" >> ~/.msmtprc
          echo "port           587" >> ~/.msmtprc
          echo "from           ${{ secrets.GMAIL_USER }}" >> ~/.msmtprc
          echo "user           ${{ secrets.GMAIL_USER }}" >> ~/.msmtprc
          echo "password       ${{ secrets.GMAIL_PASS }}" >> ~/.msmtprc
          echo "account default : gmail" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

          echo -e "Subject: 📣 ${{ inputs.PRODUCT_NAME }} Deployment - ${{ inputs.DEPLOYMENT_STATUS }}\n\n✅ Deployment Details:\n\nProduct     : ${{ inputs.PRODUCT_NAME }}\nEnvironment : ${{ inputs.ENVIRONMENT }}\nBranch      : ${{ inputs.ARTIFACT_BRANCH }}\nVersion     : ${{ inputs.ARTIFACT_VERSION }}\nStatus      : ${{ inputs.DEPLOYMENT_STATUS }}\nTriggered By: ${{ github.actor }}\nRun ID      : ${{ github.run_id }}\nRepo        : ${{ github.repository }}" | msmtp "${{ secrets.EMAIL_TO }}"
