name: Terraform Destroy with Gmail Notification

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./ec2_module/test
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./ec2_module/test
        run: terraform destroy --var-file="test.tfvars" -auto-approve -input=false

      - name: Send Gmail Notification (Destroy Complete)
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp-mta mailutils jq

          echo "defaults" > ~/.msmtprc
          echo "auth           on" >> ~/.msmtprc
          echo "tls            on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "account        gmail" >> ~/.msmtprc
          echo "host           smtp.gmail.com" >> ~/.msmtprc
          echo "port           587" >> ~/.msmtprc
          echo "from           $GMAIL_USER" >> ~/.msmtprc
          echo "user           $GMAIL_USER" >> ~/.msmtprc
          echo "password       $GMAIL_PASS" >> ~/.msmtprc
          echo "account default : gmail" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

          echo -e "Subject: ⚠️ Terraform Destroy Triggered\n\nResources have been destroyed from repo: ${{ github.repository }}\n\nTriggered By: ${{ github.actor }}" | msmtp $EMAIL_TO
