name: Terraform Apply with Gmail Notification

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment metadata
        id: set-meta
        run: |
          echo "PRODUCT_NAME=EC2Module" >> $GITHUB_ENV
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "TEAM=cloud-team" >> $GITHUB_ENV
          echo "VERSION=v1.0.1" >> $GITHUB_ENV
          echo "SERVICE=ec2" >> $GITHUB_ENV
          echo "CLUSTER=sandbox" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./ec2_module/test
        run: terraform init

      - name: Terraform Plan
        working-directory: ./ec2_module/test
        run: terraform plan --var-file="test.tfvars" -input=false

      - name: Terraform Apply
        working-directory: ./ec2_module/test
        run: terraform apply --var-file="test.tfvars" -auto-approve -input=false

      - name: Send Gmail Notification
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp-mta mailutils jq

          echo "defaults" > ~/.msmtprc
          echo "auth           on" >> ~/.msmtprc
          echo "tls            on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "account        gmail" >> ~/.msmtprc
          echo "host           smtp.gmail.com" >> ~/.msmtprc
          echo "port           587" >> ~/.msmtprc
          echo "from           $GMAIL_USER" >> ~/.msmtprc
          echo "user           $GMAIL_USER" >> ~/.msmtprc
          echo "password       $GMAIL_PASS" >> ~/.msmtprc
          echo "account default : gmail" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

          echo -e "Subject: ✅ Terraform Apply: $PRODUCT_NAME ($ENVIRONMENT)\n\n✅ Terraform Apply Successful\n\nProduct     : $PRODUCT_NAME\nEnvironment : $ENVIRONMENT\nTeam        : $TEAM\nService     : $SERVICE\nVersion     : $VERSION\nCluster     : $CLUSTER\nRepository  : ${{ github.repository }}\nTriggered By: ${{ github.actor }}" | msmtp $EMAIL_TO
