name: Terraform Apply with Gmail Notification

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment metadata
        id: set-meta
        run: |
          echo "PRODUCT_NAME=EC2Module" >> $GITHUB_ENV
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "TEAM=cloud-team" >> $GITHUB_ENV
          echo "VERSION=v1.0.1" >> $GITHUB_ENV
          echo "SERVICE=ec2" >> $GITHUB_ENV
          echo "CLUSTER=sandbox" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./ec2_module/test
        run: terraform init

      - name: Terraform Plan
        working-directory: ./ec2_module/test
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./ec2_module/test
        run: terraform apply -auto-approve

      - name: Send Gmail Notification
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp-mta mailutils jq

          printf "%s\n" \
            "defaults" \
            "tls on" \
            "tls_starttls on" \
            "auth on" \
            "host smtp.gmail.com" \
            "port 587" \
            "user $GMAIL_USER" \
            "password $GMAIL_PASS" \
            "from $GMAIL_USER" \
            "logfile ~/.msmtp.log" > ~/.msmtprc

          chmod 600 ~/.msmtprc

          echo "✅ Terraform Apply Successful" > email.txt
          echo >> email.txt
          echo "Product     : $PRODUCT_NAME" >> email.txt
          echo "Environment : $ENVIRONMENT" >> email.txt
          echo "Team        : $TEAM" >> email.txt
          echo "Service     : $SERVICE" >> email.txt
          echo "Version     : $VERSION" >> email.txt
          echo "Cluster     : $CLUSTER" >> email.txt
          echo "Repository  : ${{ github.repository }}" >> email.txt
          echo "Triggered By: ${{ github.actor }}" >> email.txt

          mail -s "✅ Terraform Apply: $PRODUCT_NAME ($ENVIRONMENT)" -aFrom:$GMAIL_USER $EMAIL_TO < email.txt
