name: Terraform Deploy with Gmail Notification

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_META_JSON: ${{ steps.set-meta.outputs.DEPLOY_META_JSON }}
      result: ${{ steps.set-status.outputs.result }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Deployment Metadata (base64 encoded JSON)
        id: set-meta
        run: |
          RAW_JSON='{
            "PRODUCT_NAME": "EC2Module",
            "ENVIRONMENT": "dev",
            "TEAM": "cloud-team",
            "VERSION": "v1.0.1",
            "SERVICE": "ec2",
            "CLUSTER": "sandbox",
            "BUILD_ID": "build-45873",
            "OWNER": "Mahesh Varma",
            "DEPLOY_TIME": "'"$(date -u +'%Y-%m-%dT%H:%M:%SZ')"'",
            "COMPONENT": "backend",
            "TAGS": "qa,automation,aws"
          }'
          ENCODED_JSON=$(echo "$RAW_JSON" | base64 -w0)
          echo "DEPLOY_META_JSON=$ENCODED_JSON" >> $GITHUB_ENV
          echo "DEPLOY_META_JSON=$ENCODED_JSON" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./ec2_module/test
        run: terraform init

      - name: Terraform Plan
        working-directory: ./ec2_module/test
        run: terraform plan --var-file="test.tfvars" -input=false

      - name: Terraform Apply
        working-directory: ./ec2_module/test
        run: terraform apply --var-file="test.tfvars" -auto-approve -input=false

      - name: Set Status Output
        id: set-status
        run: echo "result=success" >> $GITHUB_OUTPUT

  notify:
    needs: deploy
    uses: ./.github/workflows/gmailNotification.yaml
    with:
      DEPLOY_META_JSON: ${{ needs.deploy.outputs.DEPLOY_META_JSON }}
    secrets:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
